#!/bin/bash

if ! [[ -f bin/client ]]; then
    echo "Are you sure you ran make ?" 1&>2
    exit 66
fi

LD_LIBRARY_PATH=omniORB-4.1.7/lib:$LD_LIBRARY_PATH bin/client -ORBInitRef NameService=corbaname::$1 $2 $(hostname -I | cut -d ' ' -f 1)
